### ISSUE TITLE
Project Feedback

### ISSUE THREAD

**Issue by imaginetheheadline** [BillyHoke/tic-tac-toe#8]
# Project 1

Really great work. Solutions looks good, simple and elegant. I like the extra things you put in like audio and the use of localStorage.

## HTML

Looks pretty clean, watch the formatting:

```html
 <div class="boxes">
            <div id="b1"></div>
            <div id="b2"></div>
            <div id="b3"></div>
            <div id="b4"></div>
            <div id="b5"></div>
            <div id="b6"></div>
            <div id="b7"></div>
            <div id="b8"></div>
            <div id="b9"></div>
            </div>
        </div>
    </div>
```

There are a few too many `</div>` tags here hmm.

## CSS

CSS looks quite good! Just watch the formatting at times:

```css
.logo {
width: 400px;
height: auto;
margin-top: 10px;
}
```

Why do you have some CSS in a style tag (index.html) while some in style.css?

### Cell borders

You've got each of your cells with a different id b1..b9, which I can see you're using to check the win conditions which is fine, but it looks like you're also using it to style the borders different. For that I might recommend two options:

1. You can use grid to your advantage here. Just set a gap of 2px and background colour of `#f8e981` on the `.boxes` element. Then make each box have a background of black. As long as the boxes take up the whole grid div, you'll achieve a nice hash pattern without using custom borders. The background of the grid container will show through in the gaps to make your lines.

2. You might be interested to know about CSS's `:nth-child` selector, though I'm not really sure it's particularly better than using ids here since you're using id's anyway in your JavaScript. I think the main idea here would be actually to reduce your repetition of common CSS by using selectors like this:

```css
.boxes > div {
    display: flex;
    justify-content: center;
    align-items: center;
    color: #f8e981;
}

#b1, #b2, #b4, #b5 {
    border-right: 2px solid #f8e981;
    border-bottom: 2px solid #f8e981;
}

#b3, #b6 {
    border-bottom: 2px solid #f8e981;
}

#b7, #b8 {
    border-right: 2px solid #f8e981;
}
```

This condenses your css quite a bit. `.boxes > div:nth-child(1)` would select the same div as `#b1` if you wanted to use `:nth-child` instead.

However, to get the full benefit of that, you can use math patterns to select particular elements:

```css
.boxes > div {
    display: flex;
    justify-content: center;
    align-items: center;
    color: #f8e981;
}

/* Every third element starting with the first, and
   every third element starting with the second */
.boxes > div:nth-child(3n-1),
.boxes > div:nth-child(3n-2) {
    border-right: 2px solid #f8e981;
}

/* First 6 elements */
.boxes > div:nth-child(-n+6) {
    border-bottom: 2px solid #f8e981;
}
```

## JavaScript

Nice work, I like how you've declared all your variables first so they are available, and your functions are all nicely organised at the bottom of the file, with your main code running right at the beginning of the file. Makes it really easy to follow.

### Audio Context

Looks like you were exploring this option but then found that you can play audio using `audio` elements?

Does this do anything anymore?

```js
const AudioContext = window.AudioContext || window.webkitAudioContext;
const audioContext = new AudioContext();
```

### Array vs Object

Looks like there's a mismatch here. You're using an Array, but you're also using it as an object:

```js
winStatus.push(id);
winStatus[id] = currentPlayer;
```

This works because arrays are technically objects. However it's not a great practice. I might suggest to simply use it as an object, and you can check the size using the following:

```js
let winStatus = {}
//
winStatus[id] = currentPlayer;
//
if(Object.keys(winStatus).length == 9)
```

### displayWinner

Nice work with the `createElement` stuff in display winner and use of setTimeout to delay the sound.

Also `boxElement.style.pointerEvents = 'none';` Nice way to prevent clicks.

### localStorage

Nice job with localStorate to persist the state of player names.
